# Basic
title: Lingdingyang
subtitle: Stay Hunger, Stay Foolish
# welcome_message: 
description: Want to be a generalist, able to take on a wide variety of different work.
creator: <a href="http://zaang.github.io">@zaang</a>

# url: "http://zaang.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://zaang.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
# comment:
    # disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: dingjeng
    github: zaang
    twitter: dingzaang
    # gplus: 
    # mail: 

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
